// Code generated by fastssz. DO NOT EDIT.
package enginev2

import (
	v1 "github.com/OffchainLabs/prysm/v7/proto/engine/v1"
	ssz "github.com/prysmaticlabs/fastssz"
)

// MarshalSSZ ssz marshals the PayloadStatus object
func (p *PayloadStatus) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(p)
}

// MarshalSSZTo ssz marshals the PayloadStatus object to a target array
func (p *PayloadStatus) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	offset := int(9)

	// Field (0) 'Status'
	if size := len(p.Status); size != 1 {
		err = ssz.ErrBytesLengthFn("--.Status", size, 1)
		return
	}
	dst = append(dst, p.Status...)

	// Offset (1) 'LatestValidHash'
	dst = ssz.WriteOffset(dst, offset)
	offset += len(p.LatestValidHash) * 32

	// Offset (2) 'ValidationError'
	dst = ssz.WriteOffset(dst, offset)
	for ii := 0; ii < len(p.ValidationError); ii++ {
		offset += 4
		offset += len(p.ValidationError[ii])
	}

	// Field (1) 'LatestValidHash'
	if size := len(p.LatestValidHash); size > 1 {
		err = ssz.ErrListTooBigFn("--.LatestValidHash", size, 1)
		return
	}
	for ii := 0; ii < len(p.LatestValidHash); ii++ {
		if size := len(p.LatestValidHash[ii]); size != 32 {
			err = ssz.ErrBytesLengthFn("--.LatestValidHash[ii]", size, 32)
			return
		}
		dst = append(dst, p.LatestValidHash[ii]...)
	}

	// Field (2) 'ValidationError'
	if size := len(p.ValidationError); size > 1 {
		err = ssz.ErrListTooBigFn("--.ValidationError", size, 1)
		return
	}
	{
		offset = 4 * len(p.ValidationError)
		for ii := 0; ii < len(p.ValidationError); ii++ {
			dst = ssz.WriteOffset(dst, offset)
			offset += len(p.ValidationError[ii])
		}
	}
	for ii := 0; ii < len(p.ValidationError); ii++ {
		if size := len(p.ValidationError[ii]); size > 1024 {
			err = ssz.ErrBytesLengthFn("--.ValidationError[ii]", size, 1024)
			return
		}
		dst = append(dst, p.ValidationError[ii]...)
	}

	return
}

// UnmarshalSSZ ssz unmarshals the PayloadStatus object
func (p *PayloadStatus) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 9 {
		return ssz.ErrSize
	}

	tail := buf
	var o1, o2 uint64

	// Field (0) 'Status'
	if cap(p.Status) == 0 {
		p.Status = make([]byte, 0, len(buf[0:1]))
	}
	p.Status = append(p.Status, buf[0:1]...)

	// Offset (1) 'LatestValidHash'
	if o1 = ssz.ReadOffset(buf[1:5]); o1 > size {
		return ssz.ErrOffset
	}

	if o1 != 9 {
		return ssz.ErrInvalidVariableOffset
	}

	// Offset (2) 'ValidationError'
	if o2 = ssz.ReadOffset(buf[5:9]); o2 > size || o1 > o2 {
		return ssz.ErrOffset
	}

	// Field (1) 'LatestValidHash'
	{
		buf = tail[o1:o2]
		num, err := ssz.DivideInt2(len(buf), 32, 1)
		if err != nil {
			return err
		}
		p.LatestValidHash = make([][]byte, num)
		for ii := 0; ii < num; ii++ {
			if cap(p.LatestValidHash[ii]) == 0 {
				p.LatestValidHash[ii] = make([]byte, 0, len(buf[ii*32:(ii+1)*32]))
			}
			p.LatestValidHash[ii] = append(p.LatestValidHash[ii], buf[ii*32:(ii+1)*32]...)
		}
	}

	// Field (2) 'ValidationError'
	{
		buf = tail[o2:]
		num, err := ssz.DecodeDynamicLength(buf, 1)
		if err != nil {
			return err
		}
		p.ValidationError = make([][]byte, num)
		err = ssz.UnmarshalDynamic(buf, num, func(indx int, buf []byte) (err error) {
			if len(buf) > 1024 {
				return ssz.ErrBytesLength
			}
			if cap(p.ValidationError[indx]) == 0 {
				p.ValidationError[indx] = make([]byte, 0, len(buf))
			}
			p.ValidationError[indx] = append(p.ValidationError[indx], buf...)
			return nil
		})
		if err != nil {
			return err
		}
	}
	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the PayloadStatus object
func (p *PayloadStatus) SizeSSZ() (size int) {
	size = 9

	// Field (1) 'LatestValidHash'
	size += len(p.LatestValidHash) * 32

	// Field (2) 'ValidationError'
	for ii := 0; ii < len(p.ValidationError); ii++ {
		size += 4
		size += len(p.ValidationError[ii])
	}

	return
}

// HashTreeRoot ssz hashes the PayloadStatus object
func (p *PayloadStatus) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(p)
}

// HashTreeRootWith ssz hashes the PayloadStatus object with a hasher
func (p *PayloadStatus) HashTreeRootWith(hh *ssz.Hasher) (err error) {
	indx := hh.Index()

	// Field (0) 'Status'
	if size := len(p.Status); size != 1 {
		err = ssz.ErrBytesLengthFn("--.Status", size, 1)
		return
	}
	hh.PutBytes(p.Status)

	// Field (1) 'LatestValidHash'
	{
		if size := len(p.LatestValidHash); size > 1 {
			err = ssz.ErrListTooBigFn("--.LatestValidHash", size, 1)
			return
		}
		subIndx := hh.Index()
		for _, i := range p.LatestValidHash {
			if len(i) != 32 {
				err = ssz.ErrBytesLength
				return
			}
			hh.Append(i)
		}

		numItems := uint64(len(p.LatestValidHash))
		hh.MerkleizeWithMixin(subIndx, numItems, 1)
	}

	// Field (2) 'ValidationError'
	{
		subIndx := hh.Index()
		num := uint64(len(p.ValidationError))
		if num > 1 {
			err = ssz.ErrIncorrectListSize
			return
		}
		for _, elem := range p.ValidationError {
			{
				elemIndx := hh.Index()
				byteLen := uint64(len(elem))
				if byteLen > 1024 {
					err = ssz.ErrIncorrectListSize
					return
				}
				hh.AppendBytes32(elem)
				hh.MerkleizeWithMixin(elemIndx, byteLen, (1024+31)/32)
			}
		}
		hh.MerkleizeWithMixin(subIndx, num, 1)
	}

	hh.Merkleize(indx)
	return
}

// MarshalSSZ ssz marshals the ForkchoiceUpdateResponse object
func (f *ForkchoiceUpdateResponse) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(f)
}

// MarshalSSZTo ssz marshals the ForkchoiceUpdateResponse object to a target array
func (f *ForkchoiceUpdateResponse) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	offset := int(8)

	// Offset (0) 'PayloadStatus'
	dst = ssz.WriteOffset(dst, offset)
	if f.PayloadStatus == nil {
		f.PayloadStatus = new(PayloadStatus)
	}
	offset += f.PayloadStatus.SizeSSZ()

	// Offset (1) 'PayloadId'
	dst = ssz.WriteOffset(dst, offset)
	offset += len(f.PayloadId) * 8

	// Field (0) 'PayloadStatus'
	if dst, err = f.PayloadStatus.MarshalSSZTo(dst); err != nil {
		return
	}

	// Field (1) 'PayloadId'
	if size := len(f.PayloadId); size > 1 {
		err = ssz.ErrListTooBigFn("--.PayloadId", size, 1)
		return
	}
	for ii := 0; ii < len(f.PayloadId); ii++ {
		if size := len(f.PayloadId[ii]); size != 8 {
			err = ssz.ErrBytesLengthFn("--.PayloadId[ii]", size, 8)
			return
		}
		dst = append(dst, f.PayloadId[ii]...)
	}

	return
}

// UnmarshalSSZ ssz unmarshals the ForkchoiceUpdateResponse object
func (f *ForkchoiceUpdateResponse) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 8 {
		return ssz.ErrSize
	}

	tail := buf
	var o0, o1 uint64

	// Offset (0) 'PayloadStatus'
	if o0 = ssz.ReadOffset(buf[0:4]); o0 > size {
		return ssz.ErrOffset
	}

	if o0 != 8 {
		return ssz.ErrInvalidVariableOffset
	}

	// Offset (1) 'PayloadId'
	if o1 = ssz.ReadOffset(buf[4:8]); o1 > size || o0 > o1 {
		return ssz.ErrOffset
	}

	// Field (0) 'PayloadStatus'
	{
		buf = tail[o0:o1]
		if f.PayloadStatus == nil {
			f.PayloadStatus = new(PayloadStatus)
		}
		if err = f.PayloadStatus.UnmarshalSSZ(buf); err != nil {
			return err
		}
	}

	// Field (1) 'PayloadId'
	{
		buf = tail[o1:]
		num, err := ssz.DivideInt2(len(buf), 8, 1)
		if err != nil {
			return err
		}
		f.PayloadId = make([][]byte, num)
		for ii := 0; ii < num; ii++ {
			if cap(f.PayloadId[ii]) == 0 {
				f.PayloadId[ii] = make([]byte, 0, len(buf[ii*8:(ii+1)*8]))
			}
			f.PayloadId[ii] = append(f.PayloadId[ii], buf[ii*8:(ii+1)*8]...)
		}
	}
	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the ForkchoiceUpdateResponse object
func (f *ForkchoiceUpdateResponse) SizeSSZ() (size int) {
	size = 8

	// Field (0) 'PayloadStatus'
	if f.PayloadStatus == nil {
		f.PayloadStatus = new(PayloadStatus)
	}
	size += f.PayloadStatus.SizeSSZ()

	// Field (1) 'PayloadId'
	size += len(f.PayloadId) * 8

	return
}

// HashTreeRoot ssz hashes the ForkchoiceUpdateResponse object
func (f *ForkchoiceUpdateResponse) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(f)
}

// HashTreeRootWith ssz hashes the ForkchoiceUpdateResponse object with a hasher
func (f *ForkchoiceUpdateResponse) HashTreeRootWith(hh *ssz.Hasher) (err error) {
	indx := hh.Index()

	// Field (0) 'PayloadStatus'
	if err = f.PayloadStatus.HashTreeRootWith(hh); err != nil {
		return
	}

	// Field (1) 'PayloadId'
	{
		if size := len(f.PayloadId); size > 1 {
			err = ssz.ErrListTooBigFn("--.PayloadId", size, 1)
			return
		}
		subIndx := hh.Index()
		for _, i := range f.PayloadId {
			if len(i) != 8 {
				err = ssz.ErrBytesLength
				return
			}
			hh.PutBytes(i)
		}

		numItems := uint64(len(f.PayloadId))
		hh.MerkleizeWithMixin(subIndx, numItems, 1)
	}

	hh.Merkleize(indx)
	return
}

// MarshalSSZ ssz marshals the BodiesByHashRequest object
func (b *BodiesByHashRequest) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(b)
}

// MarshalSSZTo ssz marshals the BodiesByHashRequest object to a target array
func (b *BodiesByHashRequest) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	offset := int(4)

	// Offset (0) 'BlockHashes'
	dst = ssz.WriteOffset(dst, offset)
	offset += len(b.BlockHashes) * 32

	// Field (0) 'BlockHashes'
	if size := len(b.BlockHashes); size > 32 {
		err = ssz.ErrListTooBigFn("--.BlockHashes", size, 32)
		return
	}
	for ii := 0; ii < len(b.BlockHashes); ii++ {
		if size := len(b.BlockHashes[ii]); size != 32 {
			err = ssz.ErrBytesLengthFn("--.BlockHashes[ii]", size, 32)
			return
		}
		dst = append(dst, b.BlockHashes[ii]...)
	}

	return
}

// UnmarshalSSZ ssz unmarshals the BodiesByHashRequest object
func (b *BodiesByHashRequest) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 4 {
		return ssz.ErrSize
	}

	tail := buf
	var o0 uint64

	// Offset (0) 'BlockHashes'
	if o0 = ssz.ReadOffset(buf[0:4]); o0 > size {
		return ssz.ErrOffset
	}

	if o0 != 4 {
		return ssz.ErrInvalidVariableOffset
	}

	// Field (0) 'BlockHashes'
	{
		buf = tail[o0:]
		num, err := ssz.DivideInt2(len(buf), 32, 32)
		if err != nil {
			return err
		}
		b.BlockHashes = make([][]byte, num)
		for ii := 0; ii < num; ii++ {
			if cap(b.BlockHashes[ii]) == 0 {
				b.BlockHashes[ii] = make([]byte, 0, len(buf[ii*32:(ii+1)*32]))
			}
			b.BlockHashes[ii] = append(b.BlockHashes[ii], buf[ii*32:(ii+1)*32]...)
		}
	}
	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the BodiesByHashRequest object
func (b *BodiesByHashRequest) SizeSSZ() (size int) {
	size = 4

	// Field (0) 'BlockHashes'
	size += len(b.BlockHashes) * 32

	return
}

// HashTreeRoot ssz hashes the BodiesByHashRequest object
func (b *BodiesByHashRequest) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(b)
}

// HashTreeRootWith ssz hashes the BodiesByHashRequest object with a hasher
func (b *BodiesByHashRequest) HashTreeRootWith(hh *ssz.Hasher) (err error) {
	indx := hh.Index()

	// Field (0) 'BlockHashes'
	{
		if size := len(b.BlockHashes); size > 32 {
			err = ssz.ErrListTooBigFn("--.BlockHashes", size, 32)
			return
		}
		subIndx := hh.Index()
		for _, i := range b.BlockHashes {
			if len(i) != 32 {
				err = ssz.ErrBytesLength
				return
			}
			hh.Append(i)
		}

		numItems := uint64(len(b.BlockHashes))
		hh.MerkleizeWithMixin(subIndx, numItems, 32)
	}

	hh.Merkleize(indx)
	return
}

// MarshalSSZ ssz marshals the BlobsRequest object
func (b *BlobsRequest) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(b)
}

// MarshalSSZTo ssz marshals the BlobsRequest object to a target array
func (b *BlobsRequest) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	offset := int(4)

	// Offset (0) 'VersionedHashes'
	dst = ssz.WriteOffset(dst, offset)
	offset += len(b.VersionedHashes) * 32

	// Field (0) 'VersionedHashes'
	if size := len(b.VersionedHashes); size > 128 {
		err = ssz.ErrListTooBigFn("--.VersionedHashes", size, 128)
		return
	}
	for ii := 0; ii < len(b.VersionedHashes); ii++ {
		if size := len(b.VersionedHashes[ii]); size != 32 {
			err = ssz.ErrBytesLengthFn("--.VersionedHashes[ii]", size, 32)
			return
		}
		dst = append(dst, b.VersionedHashes[ii]...)
	}

	return
}

// UnmarshalSSZ ssz unmarshals the BlobsRequest object
func (b *BlobsRequest) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 4 {
		return ssz.ErrSize
	}

	tail := buf
	var o0 uint64

	// Offset (0) 'VersionedHashes'
	if o0 = ssz.ReadOffset(buf[0:4]); o0 > size {
		return ssz.ErrOffset
	}

	if o0 != 4 {
		return ssz.ErrInvalidVariableOffset
	}

	// Field (0) 'VersionedHashes'
	{
		buf = tail[o0:]
		num, err := ssz.DivideInt2(len(buf), 32, 128)
		if err != nil {
			return err
		}
		b.VersionedHashes = make([][]byte, num)
		for ii := 0; ii < num; ii++ {
			if cap(b.VersionedHashes[ii]) == 0 {
				b.VersionedHashes[ii] = make([]byte, 0, len(buf[ii*32:(ii+1)*32]))
			}
			b.VersionedHashes[ii] = append(b.VersionedHashes[ii], buf[ii*32:(ii+1)*32]...)
		}
	}
	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the BlobsRequest object
func (b *BlobsRequest) SizeSSZ() (size int) {
	size = 4

	// Field (0) 'VersionedHashes'
	size += len(b.VersionedHashes) * 32

	return
}

// HashTreeRoot ssz hashes the BlobsRequest object
func (b *BlobsRequest) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(b)
}

// HashTreeRootWith ssz hashes the BlobsRequest object with a hasher
func (b *BlobsRequest) HashTreeRootWith(hh *ssz.Hasher) (err error) {
	indx := hh.Index()

	// Field (0) 'VersionedHashes'
	{
		if size := len(b.VersionedHashes); size > 128 {
			err = ssz.ErrListTooBigFn("--.VersionedHashes", size, 128)
			return
		}
		subIndx := hh.Index()
		for _, i := range b.VersionedHashes {
			if len(i) != 32 {
				err = ssz.ErrBytesLength
				return
			}
			hh.Append(i)
		}

		numItems := uint64(len(b.VersionedHashes))
		hh.MerkleizeWithMixin(subIndx, numItems, 128)
	}

	hh.Merkleize(indx)
	return
}

// MarshalSSZ ssz marshals the ForkchoiceUpdateFulu object
func (f *ForkchoiceUpdateFulu) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(f)
}

// MarshalSSZTo ssz marshals the ForkchoiceUpdateFulu object to a target array
func (f *ForkchoiceUpdateFulu) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	offset := int(100)

	// Field (0) 'ForkchoiceState'
	if f.ForkchoiceState == nil {
		f.ForkchoiceState = new(v1.ForkchoiceState)
	}
	if dst, err = f.ForkchoiceState.MarshalSSZTo(dst); err != nil {
		return
	}

	// Offset (1) 'PayloadAttributes'
	dst = ssz.WriteOffset(dst, offset)
	for ii := 0; ii < len(f.PayloadAttributes); ii++ {
		offset += 4
		offset += f.PayloadAttributes[ii].SizeSSZ()
	}

	// Field (1) 'PayloadAttributes'
	if size := len(f.PayloadAttributes); size > 1 {
		err = ssz.ErrListTooBigFn("--.PayloadAttributes", size, 1)
		return
	}
	{
		offset = 4 * len(f.PayloadAttributes)
		for ii := 0; ii < len(f.PayloadAttributes); ii++ {
			dst = ssz.WriteOffset(dst, offset)
			offset += f.PayloadAttributes[ii].SizeSSZ()
		}
	}
	for ii := 0; ii < len(f.PayloadAttributes); ii++ {
		if dst, err = f.PayloadAttributes[ii].MarshalSSZTo(dst); err != nil {
			return
		}
	}

	return
}

// UnmarshalSSZ ssz unmarshals the ForkchoiceUpdateFulu object
func (f *ForkchoiceUpdateFulu) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 100 {
		return ssz.ErrSize
	}

	tail := buf
	var o1 uint64

	// Field (0) 'ForkchoiceState'
	if f.ForkchoiceState == nil {
		f.ForkchoiceState = new(v1.ForkchoiceState)
	}
	if err = f.ForkchoiceState.UnmarshalSSZ(buf[0:96]); err != nil {
		return err
	}

	// Offset (1) 'PayloadAttributes'
	if o1 = ssz.ReadOffset(buf[96:100]); o1 > size {
		return ssz.ErrOffset
	}

	if o1 != 100 {
		return ssz.ErrInvalidVariableOffset
	}

	// Field (1) 'PayloadAttributes'
	{
		buf = tail[o1:]
		num, err := ssz.DecodeDynamicLength(buf, 1)
		if err != nil {
			return err
		}
		f.PayloadAttributes = make([]*v1.PayloadAttributesV3, num)
		err = ssz.UnmarshalDynamic(buf, num, func(indx int, buf []byte) (err error) {
			if f.PayloadAttributes[indx] == nil {
				f.PayloadAttributes[indx] = new(v1.PayloadAttributesV3)
			}
			if err = f.PayloadAttributes[indx].UnmarshalSSZ(buf); err != nil {
				return err
			}
			return nil
		})
		if err != nil {
			return err
		}
	}
	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the ForkchoiceUpdateFulu object
func (f *ForkchoiceUpdateFulu) SizeSSZ() (size int) {
	size = 100

	// Field (1) 'PayloadAttributes'
	for ii := 0; ii < len(f.PayloadAttributes); ii++ {
		size += 4
		size += f.PayloadAttributes[ii].SizeSSZ()
	}

	return
}

// HashTreeRoot ssz hashes the ForkchoiceUpdateFulu object
func (f *ForkchoiceUpdateFulu) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(f)
}

// HashTreeRootWith ssz hashes the ForkchoiceUpdateFulu object with a hasher
func (f *ForkchoiceUpdateFulu) HashTreeRootWith(hh *ssz.Hasher) (err error) {
	indx := hh.Index()

	// Field (0) 'ForkchoiceState'
	if err = f.ForkchoiceState.HashTreeRootWith(hh); err != nil {
		return
	}

	// Field (1) 'PayloadAttributes'
	{
		subIndx := hh.Index()
		num := uint64(len(f.PayloadAttributes))
		if num > 1 {
			err = ssz.ErrIncorrectListSize
			return
		}
		for _, elem := range f.PayloadAttributes {
			if err = elem.HashTreeRootWith(hh); err != nil {
				return
			}
		}
		hh.MerkleizeWithMixin(subIndx, num, 1)
	}

	hh.Merkleize(indx)
	return
}

// MarshalSSZ ssz marshals the BuiltPayloadFulu object
func (b *BuiltPayloadFulu) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(b)
}

// MarshalSSZTo ssz marshals the BuiltPayloadFulu object to a target array
func (b *BuiltPayloadFulu) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	offset := int(45)

	// Offset (0) 'Payload'
	dst = ssz.WriteOffset(dst, offset)
	if b.Payload == nil {
		b.Payload = new(v1.ExecutionPayloadDeneb)
	}
	offset += b.Payload.SizeSSZ()

	// Field (1) 'BlockValue'
	if size := len(b.BlockValue); size != 32 {
		err = ssz.ErrBytesLengthFn("--.BlockValue", size, 32)
		return
	}
	dst = append(dst, b.BlockValue...)

	// Offset (2) 'BlobsBundle'
	dst = ssz.WriteOffset(dst, offset)
	if b.BlobsBundle == nil {
		b.BlobsBundle = new(v1.BlobsBundleV2)
	}
	offset += b.BlobsBundle.SizeSSZ()

	// Offset (3) 'ExecutionRequests'
	dst = ssz.WriteOffset(dst, offset)
	for ii := 0; ii < len(b.ExecutionRequests); ii++ {
		offset += 4
		offset += len(b.ExecutionRequests[ii])
	}

	// Field (4) 'ShouldOverrideBuilder'
	dst = ssz.MarshalBool(dst, b.ShouldOverrideBuilder)

	// Field (0) 'Payload'
	if dst, err = b.Payload.MarshalSSZTo(dst); err != nil {
		return
	}

	// Field (2) 'BlobsBundle'
	if dst, err = b.BlobsBundle.MarshalSSZTo(dst); err != nil {
		return
	}

	// Field (3) 'ExecutionRequests'
	if size := len(b.ExecutionRequests); size > 256 {
		err = ssz.ErrListTooBigFn("--.ExecutionRequests", size, 256)
		return
	}
	{
		offset = 4 * len(b.ExecutionRequests)
		for ii := 0; ii < len(b.ExecutionRequests); ii++ {
			dst = ssz.WriteOffset(dst, offset)
			offset += len(b.ExecutionRequests[ii])
		}
	}
	for ii := 0; ii < len(b.ExecutionRequests); ii++ {
		if size := len(b.ExecutionRequests[ii]); size > 1073741824 {
			err = ssz.ErrBytesLengthFn("--.ExecutionRequests[ii]", size, 1073741824)
			return
		}
		dst = append(dst, b.ExecutionRequests[ii]...)
	}

	return
}

// UnmarshalSSZ ssz unmarshals the BuiltPayloadFulu object
func (b *BuiltPayloadFulu) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 45 {
		return ssz.ErrSize
	}

	tail := buf
	var o0, o2, o3 uint64

	// Offset (0) 'Payload'
	if o0 = ssz.ReadOffset(buf[0:4]); o0 > size {
		return ssz.ErrOffset
	}

	if o0 != 45 {
		return ssz.ErrInvalidVariableOffset
	}

	// Field (1) 'BlockValue'
	if cap(b.BlockValue) == 0 {
		b.BlockValue = make([]byte, 0, len(buf[4:36]))
	}
	b.BlockValue = append(b.BlockValue, buf[4:36]...)

	// Offset (2) 'BlobsBundle'
	if o2 = ssz.ReadOffset(buf[36:40]); o2 > size || o0 > o2 {
		return ssz.ErrOffset
	}

	// Offset (3) 'ExecutionRequests'
	if o3 = ssz.ReadOffset(buf[40:44]); o3 > size || o2 > o3 {
		return ssz.ErrOffset
	}

	// Field (4) 'ShouldOverrideBuilder'
	b.ShouldOverrideBuilder, err = ssz.DecodeBool(buf[44:45])
	if err != nil {
		return err
	}

	// Field (0) 'Payload'
	{
		buf = tail[o0:o2]
		if b.Payload == nil {
			b.Payload = new(v1.ExecutionPayloadDeneb)
		}
		if err = b.Payload.UnmarshalSSZ(buf); err != nil {
			return err
		}
	}

	// Field (2) 'BlobsBundle'
	{
		buf = tail[o2:o3]
		if b.BlobsBundle == nil {
			b.BlobsBundle = new(v1.BlobsBundleV2)
		}
		if err = b.BlobsBundle.UnmarshalSSZ(buf); err != nil {
			return err
		}
	}

	// Field (3) 'ExecutionRequests'
	{
		buf = tail[o3:]
		num, err := ssz.DecodeDynamicLength(buf, 256)
		if err != nil {
			return err
		}
		b.ExecutionRequests = make([][]byte, num)
		err = ssz.UnmarshalDynamic(buf, num, func(indx int, buf []byte) (err error) {
			if len(buf) > 1073741824 {
				return ssz.ErrBytesLength
			}
			if cap(b.ExecutionRequests[indx]) == 0 {
				b.ExecutionRequests[indx] = make([]byte, 0, len(buf))
			}
			b.ExecutionRequests[indx] = append(b.ExecutionRequests[indx], buf...)
			return nil
		})
		if err != nil {
			return err
		}
	}
	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the BuiltPayloadFulu object
func (b *BuiltPayloadFulu) SizeSSZ() (size int) {
	size = 45

	// Field (0) 'Payload'
	if b.Payload == nil {
		b.Payload = new(v1.ExecutionPayloadDeneb)
	}
	size += b.Payload.SizeSSZ()

	// Field (2) 'BlobsBundle'
	if b.BlobsBundle == nil {
		b.BlobsBundle = new(v1.BlobsBundleV2)
	}
	size += b.BlobsBundle.SizeSSZ()

	// Field (3) 'ExecutionRequests'
	for ii := 0; ii < len(b.ExecutionRequests); ii++ {
		size += 4
		size += len(b.ExecutionRequests[ii])
	}

	return
}

// HashTreeRoot ssz hashes the BuiltPayloadFulu object
func (b *BuiltPayloadFulu) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(b)
}

// HashTreeRootWith ssz hashes the BuiltPayloadFulu object with a hasher
func (b *BuiltPayloadFulu) HashTreeRootWith(hh *ssz.Hasher) (err error) {
	indx := hh.Index()

	// Field (0) 'Payload'
	if err = b.Payload.HashTreeRootWith(hh); err != nil {
		return
	}

	// Field (1) 'BlockValue'
	if size := len(b.BlockValue); size != 32 {
		err = ssz.ErrBytesLengthFn("--.BlockValue", size, 32)
		return
	}
	hh.PutBytes(b.BlockValue)

	// Field (2) 'BlobsBundle'
	if err = b.BlobsBundle.HashTreeRootWith(hh); err != nil {
		return
	}

	// Field (3) 'ExecutionRequests'
	{
		subIndx := hh.Index()
		num := uint64(len(b.ExecutionRequests))
		if num > 256 {
			err = ssz.ErrIncorrectListSize
			return
		}
		for _, elem := range b.ExecutionRequests {
			{
				elemIndx := hh.Index()
				byteLen := uint64(len(elem))
				if byteLen > 1073741824 {
					err = ssz.ErrIncorrectListSize
					return
				}
				hh.AppendBytes32(elem)
				hh.MerkleizeWithMixin(elemIndx, byteLen, (1073741824+31)/32)
			}
		}
		hh.MerkleizeWithMixin(subIndx, num, 256)
	}

	// Field (4) 'ShouldOverrideBuilder'
	hh.PutBool(b.ShouldOverrideBuilder)

	hh.Merkleize(indx)
	return
}

// MarshalSSZ ssz marshals the ExecutionPayloadBodyFulu object
func (e *ExecutionPayloadBodyFulu) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(e)
}

// MarshalSSZTo ssz marshals the ExecutionPayloadBodyFulu object to a target array
func (e *ExecutionPayloadBodyFulu) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	offset := int(8)

	// Offset (0) 'Transactions'
	dst = ssz.WriteOffset(dst, offset)
	for ii := 0; ii < len(e.Transactions); ii++ {
		offset += 4
		offset += len(e.Transactions[ii])
	}

	// Offset (1) 'Withdrawals'
	dst = ssz.WriteOffset(dst, offset)
	offset += len(e.Withdrawals) * 44

	// Field (0) 'Transactions'
	if size := len(e.Transactions); size > 1048576 {
		err = ssz.ErrListTooBigFn("--.Transactions", size, 1048576)
		return
	}
	{
		offset = 4 * len(e.Transactions)
		for ii := 0; ii < len(e.Transactions); ii++ {
			dst = ssz.WriteOffset(dst, offset)
			offset += len(e.Transactions[ii])
		}
	}
	for ii := 0; ii < len(e.Transactions); ii++ {
		if size := len(e.Transactions[ii]); size > 1073741824 {
			err = ssz.ErrBytesLengthFn("--.Transactions[ii]", size, 1073741824)
			return
		}
		dst = append(dst, e.Transactions[ii]...)
	}

	// Field (1) 'Withdrawals'
	if size := len(e.Withdrawals); size > 16 {
		err = ssz.ErrListTooBigFn("--.Withdrawals", size, 16)
		return
	}
	for ii := 0; ii < len(e.Withdrawals); ii++ {
		if dst, err = e.Withdrawals[ii].MarshalSSZTo(dst); err != nil {
			return
		}
	}

	return
}

// UnmarshalSSZ ssz unmarshals the ExecutionPayloadBodyFulu object
func (e *ExecutionPayloadBodyFulu) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 8 {
		return ssz.ErrSize
	}

	tail := buf
	var o0, o1 uint64

	// Offset (0) 'Transactions'
	if o0 = ssz.ReadOffset(buf[0:4]); o0 > size {
		return ssz.ErrOffset
	}

	if o0 != 8 {
		return ssz.ErrInvalidVariableOffset
	}

	// Offset (1) 'Withdrawals'
	if o1 = ssz.ReadOffset(buf[4:8]); o1 > size || o0 > o1 {
		return ssz.ErrOffset
	}

	// Field (0) 'Transactions'
	{
		buf = tail[o0:o1]
		num, err := ssz.DecodeDynamicLength(buf, 1048576)
		if err != nil {
			return err
		}
		e.Transactions = make([][]byte, num)
		err = ssz.UnmarshalDynamic(buf, num, func(indx int, buf []byte) (err error) {
			if len(buf) > 1073741824 {
				return ssz.ErrBytesLength
			}
			if cap(e.Transactions[indx]) == 0 {
				e.Transactions[indx] = make([]byte, 0, len(buf))
			}
			e.Transactions[indx] = append(e.Transactions[indx], buf...)
			return nil
		})
		if err != nil {
			return err
		}
	}

	// Field (1) 'Withdrawals'
	{
		buf = tail[o1:]
		num, err := ssz.DivideInt2(len(buf), 44, 16)
		if err != nil {
			return err
		}
		e.Withdrawals = make([]*v1.Withdrawal, num)
		for ii := 0; ii < num; ii++ {
			if e.Withdrawals[ii] == nil {
				e.Withdrawals[ii] = new(v1.Withdrawal)
			}
			if err = e.Withdrawals[ii].UnmarshalSSZ(buf[ii*44 : (ii+1)*44]); err != nil {
				return err
			}
		}
	}
	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the ExecutionPayloadBodyFulu object
func (e *ExecutionPayloadBodyFulu) SizeSSZ() (size int) {
	size = 8

	// Field (0) 'Transactions'
	for ii := 0; ii < len(e.Transactions); ii++ {
		size += 4
		size += len(e.Transactions[ii])
	}

	// Field (1) 'Withdrawals'
	size += len(e.Withdrawals) * 44

	return
}

// HashTreeRoot ssz hashes the ExecutionPayloadBodyFulu object
func (e *ExecutionPayloadBodyFulu) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(e)
}

// HashTreeRootWith ssz hashes the ExecutionPayloadBodyFulu object with a hasher
func (e *ExecutionPayloadBodyFulu) HashTreeRootWith(hh *ssz.Hasher) (err error) {
	indx := hh.Index()

	// Field (0) 'Transactions'
	{
		subIndx := hh.Index()
		num := uint64(len(e.Transactions))
		if num > 1048576 {
			err = ssz.ErrIncorrectListSize
			return
		}
		for _, elem := range e.Transactions {
			{
				elemIndx := hh.Index()
				byteLen := uint64(len(elem))
				if byteLen > 1073741824 {
					err = ssz.ErrIncorrectListSize
					return
				}
				hh.AppendBytes32(elem)
				hh.MerkleizeWithMixin(elemIndx, byteLen, (1073741824+31)/32)
			}
		}
		hh.MerkleizeWithMixin(subIndx, num, 1048576)
	}

	// Field (1) 'Withdrawals'
	{
		subIndx := hh.Index()
		num := uint64(len(e.Withdrawals))
		if num > 16 {
			err = ssz.ErrIncorrectListSize
			return
		}
		for _, elem := range e.Withdrawals {
			if err = elem.HashTreeRootWith(hh); err != nil {
				return
			}
		}
		hh.MerkleizeWithMixin(subIndx, num, 16)
	}

	hh.Merkleize(indx)
	return
}

// MarshalSSZ ssz marshals the BodyEntryFulu object
func (b *BodyEntryFulu) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(b)
}

// MarshalSSZTo ssz marshals the BodyEntryFulu object to a target array
func (b *BodyEntryFulu) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	offset := int(5)

	// Field (0) 'Available'
	dst = ssz.MarshalBool(dst, b.Available)

	// Offset (1) 'Body'
	dst = ssz.WriteOffset(dst, offset)
	if b.Body == nil {
		b.Body = new(ExecutionPayloadBodyFulu)
	}
	offset += b.Body.SizeSSZ()

	// Field (1) 'Body'
	if dst, err = b.Body.MarshalSSZTo(dst); err != nil {
		return
	}

	return
}

// UnmarshalSSZ ssz unmarshals the BodyEntryFulu object
func (b *BodyEntryFulu) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 5 {
		return ssz.ErrSize
	}

	tail := buf
	var o1 uint64

	// Field (0) 'Available'
	b.Available, err = ssz.DecodeBool(buf[0:1])
	if err != nil {
		return err
	}

	// Offset (1) 'Body'
	if o1 = ssz.ReadOffset(buf[1:5]); o1 > size {
		return ssz.ErrOffset
	}

	if o1 != 5 {
		return ssz.ErrInvalidVariableOffset
	}

	// Field (1) 'Body'
	{
		buf = tail[o1:]
		if b.Body == nil {
			b.Body = new(ExecutionPayloadBodyFulu)
		}
		if err = b.Body.UnmarshalSSZ(buf); err != nil {
			return err
		}
	}
	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the BodyEntryFulu object
func (b *BodyEntryFulu) SizeSSZ() (size int) {
	size = 5

	// Field (1) 'Body'
	if b.Body == nil {
		b.Body = new(ExecutionPayloadBodyFulu)
	}
	size += b.Body.SizeSSZ()

	return
}

// HashTreeRoot ssz hashes the BodyEntryFulu object
func (b *BodyEntryFulu) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(b)
}

// HashTreeRootWith ssz hashes the BodyEntryFulu object with a hasher
func (b *BodyEntryFulu) HashTreeRootWith(hh *ssz.Hasher) (err error) {
	indx := hh.Index()

	// Field (0) 'Available'
	hh.PutBool(b.Available)

	// Field (1) 'Body'
	if err = b.Body.HashTreeRootWith(hh); err != nil {
		return
	}

	hh.Merkleize(indx)
	return
}

// MarshalSSZ ssz marshals the BodiesResponseFulu object
func (b *BodiesResponseFulu) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(b)
}

// MarshalSSZTo ssz marshals the BodiesResponseFulu object to a target array
func (b *BodiesResponseFulu) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	offset := int(4)

	// Offset (0) 'Entries'
	dst = ssz.WriteOffset(dst, offset)
	for ii := 0; ii < len(b.Entries); ii++ {
		offset += 4
		offset += b.Entries[ii].SizeSSZ()
	}

	// Field (0) 'Entries'
	if size := len(b.Entries); size > 32 {
		err = ssz.ErrListTooBigFn("--.Entries", size, 32)
		return
	}
	{
		offset = 4 * len(b.Entries)
		for ii := 0; ii < len(b.Entries); ii++ {
			dst = ssz.WriteOffset(dst, offset)
			offset += b.Entries[ii].SizeSSZ()
		}
	}
	for ii := 0; ii < len(b.Entries); ii++ {
		if dst, err = b.Entries[ii].MarshalSSZTo(dst); err != nil {
			return
		}
	}

	return
}

// UnmarshalSSZ ssz unmarshals the BodiesResponseFulu object
func (b *BodiesResponseFulu) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 4 {
		return ssz.ErrSize
	}

	tail := buf
	var o0 uint64

	// Offset (0) 'Entries'
	if o0 = ssz.ReadOffset(buf[0:4]); o0 > size {
		return ssz.ErrOffset
	}

	if o0 != 4 {
		return ssz.ErrInvalidVariableOffset
	}

	// Field (0) 'Entries'
	{
		buf = tail[o0:]
		num, err := ssz.DecodeDynamicLength(buf, 32)
		if err != nil {
			return err
		}
		b.Entries = make([]*BodyEntryFulu, num)
		err = ssz.UnmarshalDynamic(buf, num, func(indx int, buf []byte) (err error) {
			if b.Entries[indx] == nil {
				b.Entries[indx] = new(BodyEntryFulu)
			}
			if err = b.Entries[indx].UnmarshalSSZ(buf); err != nil {
				return err
			}
			return nil
		})
		if err != nil {
			return err
		}
	}
	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the BodiesResponseFulu object
func (b *BodiesResponseFulu) SizeSSZ() (size int) {
	size = 4

	// Field (0) 'Entries'
	for ii := 0; ii < len(b.Entries); ii++ {
		size += 4
		size += b.Entries[ii].SizeSSZ()
	}

	return
}

// HashTreeRoot ssz hashes the BodiesResponseFulu object
func (b *BodiesResponseFulu) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(b)
}

// HashTreeRootWith ssz hashes the BodiesResponseFulu object with a hasher
func (b *BodiesResponseFulu) HashTreeRootWith(hh *ssz.Hasher) (err error) {
	indx := hh.Index()

	// Field (0) 'Entries'
	{
		subIndx := hh.Index()
		num := uint64(len(b.Entries))
		if num > 32 {
			err = ssz.ErrIncorrectListSize
			return
		}
		for _, elem := range b.Entries {
			if err = elem.HashTreeRootWith(hh); err != nil {
				return
			}
		}
		hh.MerkleizeWithMixin(subIndx, num, 32)
	}

	hh.Merkleize(indx)
	return
}

// MarshalSSZ ssz marshals the ExecutionPayloadEnvelopeGloas object
func (e *ExecutionPayloadEnvelopeGloas) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(e)
}

// MarshalSSZTo ssz marshals the ExecutionPayloadEnvelopeGloas object to a target array
func (e *ExecutionPayloadEnvelopeGloas) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	offset := int(40)

	// Offset (0) 'Payload'
	dst = ssz.WriteOffset(dst, offset)
	if e.Payload == nil {
		e.Payload = new(v1.ExecutionPayloadGloas)
	}
	offset += e.Payload.SizeSSZ()

	// Field (1) 'ParentBeaconBlockRoot'
	if size := len(e.ParentBeaconBlockRoot); size != 32 {
		err = ssz.ErrBytesLengthFn("--.ParentBeaconBlockRoot", size, 32)
		return
	}
	dst = append(dst, e.ParentBeaconBlockRoot...)

	// Offset (2) 'ExecutionRequests'
	dst = ssz.WriteOffset(dst, offset)
	for ii := 0; ii < len(e.ExecutionRequests); ii++ {
		offset += 4
		offset += len(e.ExecutionRequests[ii])
	}

	// Field (0) 'Payload'
	if dst, err = e.Payload.MarshalSSZTo(dst); err != nil {
		return
	}

	// Field (2) 'ExecutionRequests'
	if size := len(e.ExecutionRequests); size > 256 {
		err = ssz.ErrListTooBigFn("--.ExecutionRequests", size, 256)
		return
	}
	{
		offset = 4 * len(e.ExecutionRequests)
		for ii := 0; ii < len(e.ExecutionRequests); ii++ {
			dst = ssz.WriteOffset(dst, offset)
			offset += len(e.ExecutionRequests[ii])
		}
	}
	for ii := 0; ii < len(e.ExecutionRequests); ii++ {
		if size := len(e.ExecutionRequests[ii]); size > 1073741824 {
			err = ssz.ErrBytesLengthFn("--.ExecutionRequests[ii]", size, 1073741824)
			return
		}
		dst = append(dst, e.ExecutionRequests[ii]...)
	}

	return
}

// UnmarshalSSZ ssz unmarshals the ExecutionPayloadEnvelopeGloas object
func (e *ExecutionPayloadEnvelopeGloas) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 40 {
		return ssz.ErrSize
	}

	tail := buf
	var o0, o2 uint64

	// Offset (0) 'Payload'
	if o0 = ssz.ReadOffset(buf[0:4]); o0 > size {
		return ssz.ErrOffset
	}

	if o0 != 40 {
		return ssz.ErrInvalidVariableOffset
	}

	// Field (1) 'ParentBeaconBlockRoot'
	if cap(e.ParentBeaconBlockRoot) == 0 {
		e.ParentBeaconBlockRoot = make([]byte, 0, len(buf[4:36]))
	}
	e.ParentBeaconBlockRoot = append(e.ParentBeaconBlockRoot, buf[4:36]...)

	// Offset (2) 'ExecutionRequests'
	if o2 = ssz.ReadOffset(buf[36:40]); o2 > size || o0 > o2 {
		return ssz.ErrOffset
	}

	// Field (0) 'Payload'
	{
		buf = tail[o0:o2]
		if e.Payload == nil {
			e.Payload = new(v1.ExecutionPayloadGloas)
		}
		if err = e.Payload.UnmarshalSSZ(buf); err != nil {
			return err
		}
	}

	// Field (2) 'ExecutionRequests'
	{
		buf = tail[o2:]
		num, err := ssz.DecodeDynamicLength(buf, 256)
		if err != nil {
			return err
		}
		e.ExecutionRequests = make([][]byte, num)
		err = ssz.UnmarshalDynamic(buf, num, func(indx int, buf []byte) (err error) {
			if len(buf) > 1073741824 {
				return ssz.ErrBytesLength
			}
			if cap(e.ExecutionRequests[indx]) == 0 {
				e.ExecutionRequests[indx] = make([]byte, 0, len(buf))
			}
			e.ExecutionRequests[indx] = append(e.ExecutionRequests[indx], buf...)
			return nil
		})
		if err != nil {
			return err
		}
	}
	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the ExecutionPayloadEnvelopeGloas object
func (e *ExecutionPayloadEnvelopeGloas) SizeSSZ() (size int) {
	size = 40

	// Field (0) 'Payload'
	if e.Payload == nil {
		e.Payload = new(v1.ExecutionPayloadGloas)
	}
	size += e.Payload.SizeSSZ()

	// Field (2) 'ExecutionRequests'
	for ii := 0; ii < len(e.ExecutionRequests); ii++ {
		size += 4
		size += len(e.ExecutionRequests[ii])
	}

	return
}

// HashTreeRoot ssz hashes the ExecutionPayloadEnvelopeGloas object
func (e *ExecutionPayloadEnvelopeGloas) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(e)
}

// HashTreeRootWith ssz hashes the ExecutionPayloadEnvelopeGloas object with a hasher
func (e *ExecutionPayloadEnvelopeGloas) HashTreeRootWith(hh *ssz.Hasher) (err error) {
	indx := hh.Index()

	// Field (0) 'Payload'
	if err = e.Payload.HashTreeRootWith(hh); err != nil {
		return
	}

	// Field (1) 'ParentBeaconBlockRoot'
	if size := len(e.ParentBeaconBlockRoot); size != 32 {
		err = ssz.ErrBytesLengthFn("--.ParentBeaconBlockRoot", size, 32)
		return
	}
	hh.PutBytes(e.ParentBeaconBlockRoot)

	// Field (2) 'ExecutionRequests'
	{
		subIndx := hh.Index()
		num := uint64(len(e.ExecutionRequests))
		if num > 256 {
			err = ssz.ErrIncorrectListSize
			return
		}
		for _, elem := range e.ExecutionRequests {
			{
				elemIndx := hh.Index()
				byteLen := uint64(len(elem))
				if byteLen > 1073741824 {
					err = ssz.ErrIncorrectListSize
					return
				}
				hh.AppendBytes32(elem)
				hh.MerkleizeWithMixin(elemIndx, byteLen, (1073741824+31)/32)
			}
		}
		hh.MerkleizeWithMixin(subIndx, num, 256)
	}

	hh.Merkleize(indx)
	return
}

// MarshalSSZ ssz marshals the ForkchoiceUpdateGloas object
func (f *ForkchoiceUpdateGloas) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(f)
}

// MarshalSSZTo ssz marshals the ForkchoiceUpdateGloas object to a target array
func (f *ForkchoiceUpdateGloas) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	offset := int(104)

	// Field (0) 'ForkchoiceState'
	if f.ForkchoiceState == nil {
		f.ForkchoiceState = new(v1.ForkchoiceState)
	}
	if dst, err = f.ForkchoiceState.MarshalSSZTo(dst); err != nil {
		return
	}

	// Offset (1) 'PayloadAttributes'
	dst = ssz.WriteOffset(dst, offset)
	for ii := 0; ii < len(f.PayloadAttributes); ii++ {
		offset += 4
		offset += f.PayloadAttributes[ii].SizeSSZ()
	}

	// Offset (2) 'CustodyColumns'
	dst = ssz.WriteOffset(dst, offset)
	offset += len(f.CustodyColumns) * 16

	// Field (1) 'PayloadAttributes'
	if size := len(f.PayloadAttributes); size > 1 {
		err = ssz.ErrListTooBigFn("--.PayloadAttributes", size, 1)
		return
	}
	{
		offset = 4 * len(f.PayloadAttributes)
		for ii := 0; ii < len(f.PayloadAttributes); ii++ {
			dst = ssz.WriteOffset(dst, offset)
			offset += f.PayloadAttributes[ii].SizeSSZ()
		}
	}
	for ii := 0; ii < len(f.PayloadAttributes); ii++ {
		if dst, err = f.PayloadAttributes[ii].MarshalSSZTo(dst); err != nil {
			return
		}
	}

	// Field (2) 'CustodyColumns'
	if size := len(f.CustodyColumns); size > 1 {
		err = ssz.ErrListTooBigFn("--.CustodyColumns", size, 1)
		return
	}
	for ii := 0; ii < len(f.CustodyColumns); ii++ {
		if size := len(f.CustodyColumns[ii]); size != 16 {
			err = ssz.ErrBytesLengthFn("--.CustodyColumns[ii]", size, 16)
			return
		}
		dst = append(dst, f.CustodyColumns[ii]...)
	}

	return
}

// UnmarshalSSZ ssz unmarshals the ForkchoiceUpdateGloas object
func (f *ForkchoiceUpdateGloas) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 104 {
		return ssz.ErrSize
	}

	tail := buf
	var o1, o2 uint64

	// Field (0) 'ForkchoiceState'
	if f.ForkchoiceState == nil {
		f.ForkchoiceState = new(v1.ForkchoiceState)
	}
	if err = f.ForkchoiceState.UnmarshalSSZ(buf[0:96]); err != nil {
		return err
	}

	// Offset (1) 'PayloadAttributes'
	if o1 = ssz.ReadOffset(buf[96:100]); o1 > size {
		return ssz.ErrOffset
	}

	if o1 != 104 {
		return ssz.ErrInvalidVariableOffset
	}

	// Offset (2) 'CustodyColumns'
	if o2 = ssz.ReadOffset(buf[100:104]); o2 > size || o1 > o2 {
		return ssz.ErrOffset
	}

	// Field (1) 'PayloadAttributes'
	{
		buf = tail[o1:o2]
		num, err := ssz.DecodeDynamicLength(buf, 1)
		if err != nil {
			return err
		}
		f.PayloadAttributes = make([]*v1.PayloadAttributesV4, num)
		err = ssz.UnmarshalDynamic(buf, num, func(indx int, buf []byte) (err error) {
			if f.PayloadAttributes[indx] == nil {
				f.PayloadAttributes[indx] = new(v1.PayloadAttributesV4)
			}
			if err = f.PayloadAttributes[indx].UnmarshalSSZ(buf); err != nil {
				return err
			}
			return nil
		})
		if err != nil {
			return err
		}
	}

	// Field (2) 'CustodyColumns'
	{
		buf = tail[o2:]
		num, err := ssz.DivideInt2(len(buf), 16, 1)
		if err != nil {
			return err
		}
		f.CustodyColumns = make([][]byte, num)
		for ii := 0; ii < num; ii++ {
			if cap(f.CustodyColumns[ii]) == 0 {
				f.CustodyColumns[ii] = make([]byte, 0, len(buf[ii*16:(ii+1)*16]))
			}
			f.CustodyColumns[ii] = append(f.CustodyColumns[ii], buf[ii*16:(ii+1)*16]...)
		}
	}
	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the ForkchoiceUpdateGloas object
func (f *ForkchoiceUpdateGloas) SizeSSZ() (size int) {
	size = 104

	// Field (1) 'PayloadAttributes'
	for ii := 0; ii < len(f.PayloadAttributes); ii++ {
		size += 4
		size += f.PayloadAttributes[ii].SizeSSZ()
	}

	// Field (2) 'CustodyColumns'
	size += len(f.CustodyColumns) * 16

	return
}

// HashTreeRoot ssz hashes the ForkchoiceUpdateGloas object
func (f *ForkchoiceUpdateGloas) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(f)
}

// HashTreeRootWith ssz hashes the ForkchoiceUpdateGloas object with a hasher
func (f *ForkchoiceUpdateGloas) HashTreeRootWith(hh *ssz.Hasher) (err error) {
	indx := hh.Index()

	// Field (0) 'ForkchoiceState'
	if err = f.ForkchoiceState.HashTreeRootWith(hh); err != nil {
		return
	}

	// Field (1) 'PayloadAttributes'
	{
		subIndx := hh.Index()
		num := uint64(len(f.PayloadAttributes))
		if num > 1 {
			err = ssz.ErrIncorrectListSize
			return
		}
		for _, elem := range f.PayloadAttributes {
			if err = elem.HashTreeRootWith(hh); err != nil {
				return
			}
		}
		hh.MerkleizeWithMixin(subIndx, num, 1)
	}

	// Field (2) 'CustodyColumns'
	{
		if size := len(f.CustodyColumns); size > 1 {
			err = ssz.ErrListTooBigFn("--.CustodyColumns", size, 1)
			return
		}
		subIndx := hh.Index()
		for _, i := range f.CustodyColumns {
			if len(i) != 16 {
				err = ssz.ErrBytesLength
				return
			}
			hh.PutBytes(i)
		}

		numItems := uint64(len(f.CustodyColumns))
		hh.MerkleizeWithMixin(subIndx, numItems, 1)
	}

	hh.Merkleize(indx)
	return
}

// MarshalSSZ ssz marshals the BuiltPayloadGloas object
func (b *BuiltPayloadGloas) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(b)
}

// MarshalSSZTo ssz marshals the BuiltPayloadGloas object to a target array
func (b *BuiltPayloadGloas) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	offset := int(45)

	// Offset (0) 'Payload'
	dst = ssz.WriteOffset(dst, offset)
	if b.Payload == nil {
		b.Payload = new(v1.ExecutionPayloadGloas)
	}
	offset += b.Payload.SizeSSZ()

	// Field (1) 'BlockValue'
	if size := len(b.BlockValue); size != 32 {
		err = ssz.ErrBytesLengthFn("--.BlockValue", size, 32)
		return
	}
	dst = append(dst, b.BlockValue...)

	// Offset (2) 'BlobsBundle'
	dst = ssz.WriteOffset(dst, offset)
	if b.BlobsBundle == nil {
		b.BlobsBundle = new(v1.BlobsBundleV2)
	}
	offset += b.BlobsBundle.SizeSSZ()

	// Offset (3) 'ExecutionRequests'
	dst = ssz.WriteOffset(dst, offset)
	for ii := 0; ii < len(b.ExecutionRequests); ii++ {
		offset += 4
		offset += len(b.ExecutionRequests[ii])
	}

	// Field (4) 'ShouldOverrideBuilder'
	dst = ssz.MarshalBool(dst, b.ShouldOverrideBuilder)

	// Field (0) 'Payload'
	if dst, err = b.Payload.MarshalSSZTo(dst); err != nil {
		return
	}

	// Field (2) 'BlobsBundle'
	if dst, err = b.BlobsBundle.MarshalSSZTo(dst); err != nil {
		return
	}

	// Field (3) 'ExecutionRequests'
	if size := len(b.ExecutionRequests); size > 256 {
		err = ssz.ErrListTooBigFn("--.ExecutionRequests", size, 256)
		return
	}
	{
		offset = 4 * len(b.ExecutionRequests)
		for ii := 0; ii < len(b.ExecutionRequests); ii++ {
			dst = ssz.WriteOffset(dst, offset)
			offset += len(b.ExecutionRequests[ii])
		}
	}
	for ii := 0; ii < len(b.ExecutionRequests); ii++ {
		if size := len(b.ExecutionRequests[ii]); size > 1073741824 {
			err = ssz.ErrBytesLengthFn("--.ExecutionRequests[ii]", size, 1073741824)
			return
		}
		dst = append(dst, b.ExecutionRequests[ii]...)
	}

	return
}

// UnmarshalSSZ ssz unmarshals the BuiltPayloadGloas object
func (b *BuiltPayloadGloas) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 45 {
		return ssz.ErrSize
	}

	tail := buf
	var o0, o2, o3 uint64

	// Offset (0) 'Payload'
	if o0 = ssz.ReadOffset(buf[0:4]); o0 > size {
		return ssz.ErrOffset
	}

	if o0 != 45 {
		return ssz.ErrInvalidVariableOffset
	}

	// Field (1) 'BlockValue'
	if cap(b.BlockValue) == 0 {
		b.BlockValue = make([]byte, 0, len(buf[4:36]))
	}
	b.BlockValue = append(b.BlockValue, buf[4:36]...)

	// Offset (2) 'BlobsBundle'
	if o2 = ssz.ReadOffset(buf[36:40]); o2 > size || o0 > o2 {
		return ssz.ErrOffset
	}

	// Offset (3) 'ExecutionRequests'
	if o3 = ssz.ReadOffset(buf[40:44]); o3 > size || o2 > o3 {
		return ssz.ErrOffset
	}

	// Field (4) 'ShouldOverrideBuilder'
	b.ShouldOverrideBuilder, err = ssz.DecodeBool(buf[44:45])
	if err != nil {
		return err
	}

	// Field (0) 'Payload'
	{
		buf = tail[o0:o2]
		if b.Payload == nil {
			b.Payload = new(v1.ExecutionPayloadGloas)
		}
		if err = b.Payload.UnmarshalSSZ(buf); err != nil {
			return err
		}
	}

	// Field (2) 'BlobsBundle'
	{
		buf = tail[o2:o3]
		if b.BlobsBundle == nil {
			b.BlobsBundle = new(v1.BlobsBundleV2)
		}
		if err = b.BlobsBundle.UnmarshalSSZ(buf); err != nil {
			return err
		}
	}

	// Field (3) 'ExecutionRequests'
	{
		buf = tail[o3:]
		num, err := ssz.DecodeDynamicLength(buf, 256)
		if err != nil {
			return err
		}
		b.ExecutionRequests = make([][]byte, num)
		err = ssz.UnmarshalDynamic(buf, num, func(indx int, buf []byte) (err error) {
			if len(buf) > 1073741824 {
				return ssz.ErrBytesLength
			}
			if cap(b.ExecutionRequests[indx]) == 0 {
				b.ExecutionRequests[indx] = make([]byte, 0, len(buf))
			}
			b.ExecutionRequests[indx] = append(b.ExecutionRequests[indx], buf...)
			return nil
		})
		if err != nil {
			return err
		}
	}
	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the BuiltPayloadGloas object
func (b *BuiltPayloadGloas) SizeSSZ() (size int) {
	size = 45

	// Field (0) 'Payload'
	if b.Payload == nil {
		b.Payload = new(v1.ExecutionPayloadGloas)
	}
	size += b.Payload.SizeSSZ()

	// Field (2) 'BlobsBundle'
	if b.BlobsBundle == nil {
		b.BlobsBundle = new(v1.BlobsBundleV2)
	}
	size += b.BlobsBundle.SizeSSZ()

	// Field (3) 'ExecutionRequests'
	for ii := 0; ii < len(b.ExecutionRequests); ii++ {
		size += 4
		size += len(b.ExecutionRequests[ii])
	}

	return
}

// HashTreeRoot ssz hashes the BuiltPayloadGloas object
func (b *BuiltPayloadGloas) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(b)
}

// HashTreeRootWith ssz hashes the BuiltPayloadGloas object with a hasher
func (b *BuiltPayloadGloas) HashTreeRootWith(hh *ssz.Hasher) (err error) {
	indx := hh.Index()

	// Field (0) 'Payload'
	if err = b.Payload.HashTreeRootWith(hh); err != nil {
		return
	}

	// Field (1) 'BlockValue'
	if size := len(b.BlockValue); size != 32 {
		err = ssz.ErrBytesLengthFn("--.BlockValue", size, 32)
		return
	}
	hh.PutBytes(b.BlockValue)

	// Field (2) 'BlobsBundle'
	if err = b.BlobsBundle.HashTreeRootWith(hh); err != nil {
		return
	}

	// Field (3) 'ExecutionRequests'
	{
		subIndx := hh.Index()
		num := uint64(len(b.ExecutionRequests))
		if num > 256 {
			err = ssz.ErrIncorrectListSize
			return
		}
		for _, elem := range b.ExecutionRequests {
			{
				elemIndx := hh.Index()
				byteLen := uint64(len(elem))
				if byteLen > 1073741824 {
					err = ssz.ErrIncorrectListSize
					return
				}
				hh.AppendBytes32(elem)
				hh.MerkleizeWithMixin(elemIndx, byteLen, (1073741824+31)/32)
			}
		}
		hh.MerkleizeWithMixin(subIndx, num, 256)
	}

	// Field (4) 'ShouldOverrideBuilder'
	hh.PutBool(b.ShouldOverrideBuilder)

	hh.Merkleize(indx)
	return
}

// MarshalSSZ ssz marshals the ExecutionPayloadBodyGloas object
func (e *ExecutionPayloadBodyGloas) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(e)
}

// MarshalSSZTo ssz marshals the ExecutionPayloadBodyGloas object to a target array
func (e *ExecutionPayloadBodyGloas) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	offset := int(12)

	// Offset (0) 'Transactions'
	dst = ssz.WriteOffset(dst, offset)
	for ii := 0; ii < len(e.Transactions); ii++ {
		offset += 4
		offset += len(e.Transactions[ii])
	}

	// Offset (1) 'Withdrawals'
	dst = ssz.WriteOffset(dst, offset)
	offset += len(e.Withdrawals) * 44

	// Offset (2) 'BlockAccessList'
	dst = ssz.WriteOffset(dst, offset)
	offset += len(e.BlockAccessList)

	// Field (0) 'Transactions'
	if size := len(e.Transactions); size > 1048576 {
		err = ssz.ErrListTooBigFn("--.Transactions", size, 1048576)
		return
	}
	{
		offset = 4 * len(e.Transactions)
		for ii := 0; ii < len(e.Transactions); ii++ {
			dst = ssz.WriteOffset(dst, offset)
			offset += len(e.Transactions[ii])
		}
	}
	for ii := 0; ii < len(e.Transactions); ii++ {
		if size := len(e.Transactions[ii]); size > 1073741824 {
			err = ssz.ErrBytesLengthFn("--.Transactions[ii]", size, 1073741824)
			return
		}
		dst = append(dst, e.Transactions[ii]...)
	}

	// Field (1) 'Withdrawals'
	if size := len(e.Withdrawals); size > 16 {
		err = ssz.ErrListTooBigFn("--.Withdrawals", size, 16)
		return
	}
	for ii := 0; ii < len(e.Withdrawals); ii++ {
		if dst, err = e.Withdrawals[ii].MarshalSSZTo(dst); err != nil {
			return
		}
	}

	// Field (2) 'BlockAccessList'
	if size := len(e.BlockAccessList); size > 1073741824 {
		err = ssz.ErrBytesLengthFn("--.BlockAccessList", size, 1073741824)
		return
	}
	dst = append(dst, e.BlockAccessList...)

	return
}

// UnmarshalSSZ ssz unmarshals the ExecutionPayloadBodyGloas object
func (e *ExecutionPayloadBodyGloas) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 12 {
		return ssz.ErrSize
	}

	tail := buf
	var o0, o1, o2 uint64

	// Offset (0) 'Transactions'
	if o0 = ssz.ReadOffset(buf[0:4]); o0 > size {
		return ssz.ErrOffset
	}

	if o0 != 12 {
		return ssz.ErrInvalidVariableOffset
	}

	// Offset (1) 'Withdrawals'
	if o1 = ssz.ReadOffset(buf[4:8]); o1 > size || o0 > o1 {
		return ssz.ErrOffset
	}

	// Offset (2) 'BlockAccessList'
	if o2 = ssz.ReadOffset(buf[8:12]); o2 > size || o1 > o2 {
		return ssz.ErrOffset
	}

	// Field (0) 'Transactions'
	{
		buf = tail[o0:o1]
		num, err := ssz.DecodeDynamicLength(buf, 1048576)
		if err != nil {
			return err
		}
		e.Transactions = make([][]byte, num)
		err = ssz.UnmarshalDynamic(buf, num, func(indx int, buf []byte) (err error) {
			if len(buf) > 1073741824 {
				return ssz.ErrBytesLength
			}
			if cap(e.Transactions[indx]) == 0 {
				e.Transactions[indx] = make([]byte, 0, len(buf))
			}
			e.Transactions[indx] = append(e.Transactions[indx], buf...)
			return nil
		})
		if err != nil {
			return err
		}
	}

	// Field (1) 'Withdrawals'
	{
		buf = tail[o1:o2]
		num, err := ssz.DivideInt2(len(buf), 44, 16)
		if err != nil {
			return err
		}
		e.Withdrawals = make([]*v1.Withdrawal, num)
		for ii := 0; ii < num; ii++ {
			if e.Withdrawals[ii] == nil {
				e.Withdrawals[ii] = new(v1.Withdrawal)
			}
			if err = e.Withdrawals[ii].UnmarshalSSZ(buf[ii*44 : (ii+1)*44]); err != nil {
				return err
			}
		}
	}

	// Field (2) 'BlockAccessList'
	{
		buf = tail[o2:]
		if len(buf) > 1073741824 {
			return ssz.ErrBytesLength
		}
		if cap(e.BlockAccessList) == 0 {
			e.BlockAccessList = make([]byte, 0, len(buf))
		}
		e.BlockAccessList = append(e.BlockAccessList, buf...)
	}
	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the ExecutionPayloadBodyGloas object
func (e *ExecutionPayloadBodyGloas) SizeSSZ() (size int) {
	size = 12

	// Field (0) 'Transactions'
	for ii := 0; ii < len(e.Transactions); ii++ {
		size += 4
		size += len(e.Transactions[ii])
	}

	// Field (1) 'Withdrawals'
	size += len(e.Withdrawals) * 44

	// Field (2) 'BlockAccessList'
	size += len(e.BlockAccessList)

	return
}

// HashTreeRoot ssz hashes the ExecutionPayloadBodyGloas object
func (e *ExecutionPayloadBodyGloas) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(e)
}

// HashTreeRootWith ssz hashes the ExecutionPayloadBodyGloas object with a hasher
func (e *ExecutionPayloadBodyGloas) HashTreeRootWith(hh *ssz.Hasher) (err error) {
	indx := hh.Index()

	// Field (0) 'Transactions'
	{
		subIndx := hh.Index()
		num := uint64(len(e.Transactions))
		if num > 1048576 {
			err = ssz.ErrIncorrectListSize
			return
		}
		for _, elem := range e.Transactions {
			{
				elemIndx := hh.Index()
				byteLen := uint64(len(elem))
				if byteLen > 1073741824 {
					err = ssz.ErrIncorrectListSize
					return
				}
				hh.AppendBytes32(elem)
				hh.MerkleizeWithMixin(elemIndx, byteLen, (1073741824+31)/32)
			}
		}
		hh.MerkleizeWithMixin(subIndx, num, 1048576)
	}

	// Field (1) 'Withdrawals'
	{
		subIndx := hh.Index()
		num := uint64(len(e.Withdrawals))
		if num > 16 {
			err = ssz.ErrIncorrectListSize
			return
		}
		for _, elem := range e.Withdrawals {
			if err = elem.HashTreeRootWith(hh); err != nil {
				return
			}
		}
		hh.MerkleizeWithMixin(subIndx, num, 16)
	}

	// Field (2) 'BlockAccessList'
	{
		elemIndx := hh.Index()
		byteLen := uint64(len(e.BlockAccessList))
		if byteLen > 1073741824 {
			err = ssz.ErrIncorrectListSize
			return
		}
		hh.AppendBytes32(e.BlockAccessList)
		hh.MerkleizeWithMixin(elemIndx, byteLen, (1073741824+31)/32)
	}

	hh.Merkleize(indx)
	return
}

// MarshalSSZ ssz marshals the BodyEntryGloas object
func (b *BodyEntryGloas) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(b)
}

// MarshalSSZTo ssz marshals the BodyEntryGloas object to a target array
func (b *BodyEntryGloas) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	offset := int(5)

	// Field (0) 'Available'
	dst = ssz.MarshalBool(dst, b.Available)

	// Offset (1) 'Body'
	dst = ssz.WriteOffset(dst, offset)
	if b.Body == nil {
		b.Body = new(ExecutionPayloadBodyGloas)
	}
	offset += b.Body.SizeSSZ()

	// Field (1) 'Body'
	if dst, err = b.Body.MarshalSSZTo(dst); err != nil {
		return
	}

	return
}

// UnmarshalSSZ ssz unmarshals the BodyEntryGloas object
func (b *BodyEntryGloas) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 5 {
		return ssz.ErrSize
	}

	tail := buf
	var o1 uint64

	// Field (0) 'Available'
	b.Available, err = ssz.DecodeBool(buf[0:1])
	if err != nil {
		return err
	}

	// Offset (1) 'Body'
	if o1 = ssz.ReadOffset(buf[1:5]); o1 > size {
		return ssz.ErrOffset
	}

	if o1 != 5 {
		return ssz.ErrInvalidVariableOffset
	}

	// Field (1) 'Body'
	{
		buf = tail[o1:]
		if b.Body == nil {
			b.Body = new(ExecutionPayloadBodyGloas)
		}
		if err = b.Body.UnmarshalSSZ(buf); err != nil {
			return err
		}
	}
	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the BodyEntryGloas object
func (b *BodyEntryGloas) SizeSSZ() (size int) {
	size = 5

	// Field (1) 'Body'
	if b.Body == nil {
		b.Body = new(ExecutionPayloadBodyGloas)
	}
	size += b.Body.SizeSSZ()

	return
}

// HashTreeRoot ssz hashes the BodyEntryGloas object
func (b *BodyEntryGloas) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(b)
}

// HashTreeRootWith ssz hashes the BodyEntryGloas object with a hasher
func (b *BodyEntryGloas) HashTreeRootWith(hh *ssz.Hasher) (err error) {
	indx := hh.Index()

	// Field (0) 'Available'
	hh.PutBool(b.Available)

	// Field (1) 'Body'
	if err = b.Body.HashTreeRootWith(hh); err != nil {
		return
	}

	hh.Merkleize(indx)
	return
}

// MarshalSSZ ssz marshals the BodiesResponseGloas object
func (b *BodiesResponseGloas) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(b)
}

// MarshalSSZTo ssz marshals the BodiesResponseGloas object to a target array
func (b *BodiesResponseGloas) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	offset := int(4)

	// Offset (0) 'Entries'
	dst = ssz.WriteOffset(dst, offset)
	for ii := 0; ii < len(b.Entries); ii++ {
		offset += 4
		offset += b.Entries[ii].SizeSSZ()
	}

	// Field (0) 'Entries'
	if size := len(b.Entries); size > 32 {
		err = ssz.ErrListTooBigFn("--.Entries", size, 32)
		return
	}
	{
		offset = 4 * len(b.Entries)
		for ii := 0; ii < len(b.Entries); ii++ {
			dst = ssz.WriteOffset(dst, offset)
			offset += b.Entries[ii].SizeSSZ()
		}
	}
	for ii := 0; ii < len(b.Entries); ii++ {
		if dst, err = b.Entries[ii].MarshalSSZTo(dst); err != nil {
			return
		}
	}

	return
}

// UnmarshalSSZ ssz unmarshals the BodiesResponseGloas object
func (b *BodiesResponseGloas) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 4 {
		return ssz.ErrSize
	}

	tail := buf
	var o0 uint64

	// Offset (0) 'Entries'
	if o0 = ssz.ReadOffset(buf[0:4]); o0 > size {
		return ssz.ErrOffset
	}

	if o0 != 4 {
		return ssz.ErrInvalidVariableOffset
	}

	// Field (0) 'Entries'
	{
		buf = tail[o0:]
		num, err := ssz.DecodeDynamicLength(buf, 32)
		if err != nil {
			return err
		}
		b.Entries = make([]*BodyEntryGloas, num)
		err = ssz.UnmarshalDynamic(buf, num, func(indx int, buf []byte) (err error) {
			if b.Entries[indx] == nil {
				b.Entries[indx] = new(BodyEntryGloas)
			}
			if err = b.Entries[indx].UnmarshalSSZ(buf); err != nil {
				return err
			}
			return nil
		})
		if err != nil {
			return err
		}
	}
	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the BodiesResponseGloas object
func (b *BodiesResponseGloas) SizeSSZ() (size int) {
	size = 4

	// Field (0) 'Entries'
	for ii := 0; ii < len(b.Entries); ii++ {
		size += 4
		size += b.Entries[ii].SizeSSZ()
	}

	return
}

// HashTreeRoot ssz hashes the BodiesResponseGloas object
func (b *BodiesResponseGloas) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(b)
}

// HashTreeRootWith ssz hashes the BodiesResponseGloas object with a hasher
func (b *BodiesResponseGloas) HashTreeRootWith(hh *ssz.Hasher) (err error) {
	indx := hh.Index()

	// Field (0) 'Entries'
	{
		subIndx := hh.Index()
		num := uint64(len(b.Entries))
		if num > 32 {
			err = ssz.ErrIncorrectListSize
			return
		}
		for _, elem := range b.Entries {
			if err = elem.HashTreeRootWith(hh); err != nil {
				return
			}
		}
		hh.MerkleizeWithMixin(subIndx, num, 32)
	}

	hh.Merkleize(indx)
	return
}

// MarshalSSZ ssz marshals the BlobAndProofV1 object
func (b *BlobAndProofV1) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(b)
}

// MarshalSSZTo ssz marshals the BlobAndProofV1 object to a target array
func (b *BlobAndProofV1) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf

	// Field (0) 'Blob'
	if size := len(b.Blob); size != 131072 {
		err = ssz.ErrBytesLengthFn("--.Blob", size, 131072)
		return
	}
	dst = append(dst, b.Blob...)

	// Field (1) 'Proof'
	if size := len(b.Proof); size != 48 {
		err = ssz.ErrBytesLengthFn("--.Proof", size, 48)
		return
	}
	dst = append(dst, b.Proof...)

	return
}

// UnmarshalSSZ ssz unmarshals the BlobAndProofV1 object
func (b *BlobAndProofV1) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size != 131120 {
		return ssz.ErrSize
	}

	// Field (0) 'Blob'
	if cap(b.Blob) == 0 {
		b.Blob = make([]byte, 0, len(buf[0:131072]))
	}
	b.Blob = append(b.Blob, buf[0:131072]...)

	// Field (1) 'Proof'
	if cap(b.Proof) == 0 {
		b.Proof = make([]byte, 0, len(buf[131072:131120]))
	}
	b.Proof = append(b.Proof, buf[131072:131120]...)

	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the BlobAndProofV1 object
func (b *BlobAndProofV1) SizeSSZ() (size int) {
	size = 131120
	return
}

// HashTreeRoot ssz hashes the BlobAndProofV1 object
func (b *BlobAndProofV1) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(b)
}

// HashTreeRootWith ssz hashes the BlobAndProofV1 object with a hasher
func (b *BlobAndProofV1) HashTreeRootWith(hh *ssz.Hasher) (err error) {
	indx := hh.Index()

	// Field (0) 'Blob'
	if size := len(b.Blob); size != 131072 {
		err = ssz.ErrBytesLengthFn("--.Blob", size, 131072)
		return
	}
	hh.PutBytes(b.Blob)

	// Field (1) 'Proof'
	if size := len(b.Proof); size != 48 {
		err = ssz.ErrBytesLengthFn("--.Proof", size, 48)
		return
	}
	hh.PutBytes(b.Proof)

	hh.Merkleize(indx)
	return
}

// MarshalSSZ ssz marshals the BlobV1Entry object
func (b *BlobV1Entry) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(b)
}

// MarshalSSZTo ssz marshals the BlobV1Entry object to a target array
func (b *BlobV1Entry) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf

	// Field (0) 'Available'
	dst = ssz.MarshalBool(dst, b.Available)

	// Field (1) 'Contents'
	if b.Contents == nil {
		b.Contents = new(BlobAndProofV1)
	}
	if dst, err = b.Contents.MarshalSSZTo(dst); err != nil {
		return
	}

	return
}

// UnmarshalSSZ ssz unmarshals the BlobV1Entry object
func (b *BlobV1Entry) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size != 131121 {
		return ssz.ErrSize
	}

	// Field (0) 'Available'
	b.Available, err = ssz.DecodeBool(buf[0:1])
	if err != nil {
		return err
	}

	// Field (1) 'Contents'
	if b.Contents == nil {
		b.Contents = new(BlobAndProofV1)
	}
	if err = b.Contents.UnmarshalSSZ(buf[1:131121]); err != nil {
		return err
	}

	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the BlobV1Entry object
func (b *BlobV1Entry) SizeSSZ() (size int) {
	size = 131121
	return
}

// HashTreeRoot ssz hashes the BlobV1Entry object
func (b *BlobV1Entry) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(b)
}

// HashTreeRootWith ssz hashes the BlobV1Entry object with a hasher
func (b *BlobV1Entry) HashTreeRootWith(hh *ssz.Hasher) (err error) {
	indx := hh.Index()

	// Field (0) 'Available'
	hh.PutBool(b.Available)

	// Field (1) 'Contents'
	if err = b.Contents.HashTreeRootWith(hh); err != nil {
		return
	}

	hh.Merkleize(indx)
	return
}

// MarshalSSZ ssz marshals the BlobsV1Response object
func (b *BlobsV1Response) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(b)
}

// MarshalSSZTo ssz marshals the BlobsV1Response object to a target array
func (b *BlobsV1Response) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	offset := int(4)

	// Offset (0) 'Entries'
	dst = ssz.WriteOffset(dst, offset)
	offset += len(b.Entries) * 131121

	// Field (0) 'Entries'
	if size := len(b.Entries); size > 128 {
		err = ssz.ErrListTooBigFn("--.Entries", size, 128)
		return
	}
	for ii := 0; ii < len(b.Entries); ii++ {
		if dst, err = b.Entries[ii].MarshalSSZTo(dst); err != nil {
			return
		}
	}

	return
}

// UnmarshalSSZ ssz unmarshals the BlobsV1Response object
func (b *BlobsV1Response) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 4 {
		return ssz.ErrSize
	}

	tail := buf
	var o0 uint64

	// Offset (0) 'Entries'
	if o0 = ssz.ReadOffset(buf[0:4]); o0 > size {
		return ssz.ErrOffset
	}

	if o0 != 4 {
		return ssz.ErrInvalidVariableOffset
	}

	// Field (0) 'Entries'
	{
		buf = tail[o0:]
		num, err := ssz.DivideInt2(len(buf), 131121, 128)
		if err != nil {
			return err
		}
		b.Entries = make([]*BlobV1Entry, num)
		for ii := 0; ii < num; ii++ {
			if b.Entries[ii] == nil {
				b.Entries[ii] = new(BlobV1Entry)
			}
			if err = b.Entries[ii].UnmarshalSSZ(buf[ii*131121 : (ii+1)*131121]); err != nil {
				return err
			}
		}
	}
	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the BlobsV1Response object
func (b *BlobsV1Response) SizeSSZ() (size int) {
	size = 4

	// Field (0) 'Entries'
	size += len(b.Entries) * 131121

	return
}

// HashTreeRoot ssz hashes the BlobsV1Response object
func (b *BlobsV1Response) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(b)
}

// HashTreeRootWith ssz hashes the BlobsV1Response object with a hasher
func (b *BlobsV1Response) HashTreeRootWith(hh *ssz.Hasher) (err error) {
	indx := hh.Index()

	// Field (0) 'Entries'
	{
		subIndx := hh.Index()
		num := uint64(len(b.Entries))
		if num > 128 {
			err = ssz.ErrIncorrectListSize
			return
		}
		for _, elem := range b.Entries {
			if err = elem.HashTreeRootWith(hh); err != nil {
				return
			}
		}
		hh.MerkleizeWithMixin(subIndx, num, 128)
	}

	hh.Merkleize(indx)
	return
}

// MarshalSSZ ssz marshals the BlobAndProofV2 object
func (b *BlobAndProofV2) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(b)
}

// MarshalSSZTo ssz marshals the BlobAndProofV2 object to a target array
func (b *BlobAndProofV2) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	offset := int(131076)

	// Field (0) 'Blob'
	if size := len(b.Blob); size != 131072 {
		err = ssz.ErrBytesLengthFn("--.Blob", size, 131072)
		return
	}
	dst = append(dst, b.Blob...)

	// Offset (1) 'Proofs'
	dst = ssz.WriteOffset(dst, offset)
	offset += len(b.Proofs) * 48

	// Field (1) 'Proofs'
	if size := len(b.Proofs); size > 128 {
		err = ssz.ErrListTooBigFn("--.Proofs", size, 128)
		return
	}
	for ii := 0; ii < len(b.Proofs); ii++ {
		if size := len(b.Proofs[ii]); size != 48 {
			err = ssz.ErrBytesLengthFn("--.Proofs[ii]", size, 48)
			return
		}
		dst = append(dst, b.Proofs[ii]...)
	}

	return
}

// UnmarshalSSZ ssz unmarshals the BlobAndProofV2 object
func (b *BlobAndProofV2) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 131076 {
		return ssz.ErrSize
	}

	tail := buf
	var o1 uint64

	// Field (0) 'Blob'
	if cap(b.Blob) == 0 {
		b.Blob = make([]byte, 0, len(buf[0:131072]))
	}
	b.Blob = append(b.Blob, buf[0:131072]...)

	// Offset (1) 'Proofs'
	if o1 = ssz.ReadOffset(buf[131072:131076]); o1 > size {
		return ssz.ErrOffset
	}

	if o1 != 131076 {
		return ssz.ErrInvalidVariableOffset
	}

	// Field (1) 'Proofs'
	{
		buf = tail[o1:]
		num, err := ssz.DivideInt2(len(buf), 48, 128)
		if err != nil {
			return err
		}
		b.Proofs = make([][]byte, num)
		for ii := 0; ii < num; ii++ {
			if cap(b.Proofs[ii]) == 0 {
				b.Proofs[ii] = make([]byte, 0, len(buf[ii*48:(ii+1)*48]))
			}
			b.Proofs[ii] = append(b.Proofs[ii], buf[ii*48:(ii+1)*48]...)
		}
	}
	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the BlobAndProofV2 object
func (b *BlobAndProofV2) SizeSSZ() (size int) {
	size = 131076

	// Field (1) 'Proofs'
	size += len(b.Proofs) * 48

	return
}

// HashTreeRoot ssz hashes the BlobAndProofV2 object
func (b *BlobAndProofV2) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(b)
}

// HashTreeRootWith ssz hashes the BlobAndProofV2 object with a hasher
func (b *BlobAndProofV2) HashTreeRootWith(hh *ssz.Hasher) (err error) {
	indx := hh.Index()

	// Field (0) 'Blob'
	if size := len(b.Blob); size != 131072 {
		err = ssz.ErrBytesLengthFn("--.Blob", size, 131072)
		return
	}
	hh.PutBytes(b.Blob)

	// Field (1) 'Proofs'
	{
		if size := len(b.Proofs); size > 128 {
			err = ssz.ErrListTooBigFn("--.Proofs", size, 128)
			return
		}
		subIndx := hh.Index()
		for _, i := range b.Proofs {
			if len(i) != 48 {
				err = ssz.ErrBytesLength
				return
			}
			hh.PutBytes(i)
		}

		numItems := uint64(len(b.Proofs))
		hh.MerkleizeWithMixin(subIndx, numItems, 128)
	}

	hh.Merkleize(indx)
	return
}

// MarshalSSZ ssz marshals the BlobV2Entry object
func (b *BlobV2Entry) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(b)
}

// MarshalSSZTo ssz marshals the BlobV2Entry object to a target array
func (b *BlobV2Entry) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	offset := int(5)

	// Field (0) 'Available'
	dst = ssz.MarshalBool(dst, b.Available)

	// Offset (1) 'Contents'
	dst = ssz.WriteOffset(dst, offset)
	if b.Contents == nil {
		b.Contents = new(BlobAndProofV2)
	}
	offset += b.Contents.SizeSSZ()

	// Field (1) 'Contents'
	if dst, err = b.Contents.MarshalSSZTo(dst); err != nil {
		return
	}

	return
}

// UnmarshalSSZ ssz unmarshals the BlobV2Entry object
func (b *BlobV2Entry) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 5 {
		return ssz.ErrSize
	}

	tail := buf
	var o1 uint64

	// Field (0) 'Available'
	b.Available, err = ssz.DecodeBool(buf[0:1])
	if err != nil {
		return err
	}

	// Offset (1) 'Contents'
	if o1 = ssz.ReadOffset(buf[1:5]); o1 > size {
		return ssz.ErrOffset
	}

	if o1 != 5 {
		return ssz.ErrInvalidVariableOffset
	}

	// Field (1) 'Contents'
	{
		buf = tail[o1:]
		if b.Contents == nil {
			b.Contents = new(BlobAndProofV2)
		}
		if err = b.Contents.UnmarshalSSZ(buf); err != nil {
			return err
		}
	}
	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the BlobV2Entry object
func (b *BlobV2Entry) SizeSSZ() (size int) {
	size = 5

	// Field (1) 'Contents'
	if b.Contents == nil {
		b.Contents = new(BlobAndProofV2)
	}
	size += b.Contents.SizeSSZ()

	return
}

// HashTreeRoot ssz hashes the BlobV2Entry object
func (b *BlobV2Entry) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(b)
}

// HashTreeRootWith ssz hashes the BlobV2Entry object with a hasher
func (b *BlobV2Entry) HashTreeRootWith(hh *ssz.Hasher) (err error) {
	indx := hh.Index()

	// Field (0) 'Available'
	hh.PutBool(b.Available)

	// Field (1) 'Contents'
	if err = b.Contents.HashTreeRootWith(hh); err != nil {
		return
	}

	hh.Merkleize(indx)
	return
}

// MarshalSSZ ssz marshals the BlobsV2Response object
func (b *BlobsV2Response) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(b)
}

// MarshalSSZTo ssz marshals the BlobsV2Response object to a target array
func (b *BlobsV2Response) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	offset := int(4)

	// Offset (0) 'Entries'
	dst = ssz.WriteOffset(dst, offset)
	for ii := 0; ii < len(b.Entries); ii++ {
		offset += 4
		offset += b.Entries[ii].SizeSSZ()
	}

	// Field (0) 'Entries'
	if size := len(b.Entries); size > 128 {
		err = ssz.ErrListTooBigFn("--.Entries", size, 128)
		return
	}
	{
		offset = 4 * len(b.Entries)
		for ii := 0; ii < len(b.Entries); ii++ {
			dst = ssz.WriteOffset(dst, offset)
			offset += b.Entries[ii].SizeSSZ()
		}
	}
	for ii := 0; ii < len(b.Entries); ii++ {
		if dst, err = b.Entries[ii].MarshalSSZTo(dst); err != nil {
			return
		}
	}

	return
}

// UnmarshalSSZ ssz unmarshals the BlobsV2Response object
func (b *BlobsV2Response) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 4 {
		return ssz.ErrSize
	}

	tail := buf
	var o0 uint64

	// Offset (0) 'Entries'
	if o0 = ssz.ReadOffset(buf[0:4]); o0 > size {
		return ssz.ErrOffset
	}

	if o0 != 4 {
		return ssz.ErrInvalidVariableOffset
	}

	// Field (0) 'Entries'
	{
		buf = tail[o0:]
		num, err := ssz.DecodeDynamicLength(buf, 128)
		if err != nil {
			return err
		}
		b.Entries = make([]*BlobV2Entry, num)
		err = ssz.UnmarshalDynamic(buf, num, func(indx int, buf []byte) (err error) {
			if b.Entries[indx] == nil {
				b.Entries[indx] = new(BlobV2Entry)
			}
			if err = b.Entries[indx].UnmarshalSSZ(buf); err != nil {
				return err
			}
			return nil
		})
		if err != nil {
			return err
		}
	}
	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the BlobsV2Response object
func (b *BlobsV2Response) SizeSSZ() (size int) {
	size = 4

	// Field (0) 'Entries'
	for ii := 0; ii < len(b.Entries); ii++ {
		size += 4
		size += b.Entries[ii].SizeSSZ()
	}

	return
}

// HashTreeRoot ssz hashes the BlobsV2Response object
func (b *BlobsV2Response) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(b)
}

// HashTreeRootWith ssz hashes the BlobsV2Response object with a hasher
func (b *BlobsV2Response) HashTreeRootWith(hh *ssz.Hasher) (err error) {
	indx := hh.Index()

	// Field (0) 'Entries'
	{
		subIndx := hh.Index()
		num := uint64(len(b.Entries))
		if num > 128 {
			err = ssz.ErrIncorrectListSize
			return
		}
		for _, elem := range b.Entries {
			if err = elem.HashTreeRootWith(hh); err != nil {
				return
			}
		}
		hh.MerkleizeWithMixin(subIndx, num, 128)
	}

	hh.Merkleize(indx)
	return
}
