load("@prysm//tools/go:def.bzl", "go_library")

go_library(
    name = "go_default_library",
    srcs = [
        "attack.go",
        "groups.go",
        "reorg_events.go",
    ],
    importpath = "github.com/OffchainLabs/prysm/v7/runtime/experiment",
    deps = ["//consensus-types/primitives:go_default_library"],
    visibility = ["//visibility:public"],
)
